--
-- PostgreSQL database dump
--

-- Dumped from database version 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)
-- Dumped by pg_dump version 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: Category; Type: TABLE; Schema: public; Owner: jrbuleo
--

CREATE TABLE public."Category" (
    id integer NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE public."Category" OWNER TO jrbuleo;

--
-- Name: Category_id_seq; Type: SEQUENCE; Schema: public; Owner: jrbuleo
--

CREATE SEQUENCE public."Category_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Category_id_seq" OWNER TO jrbuleo;

--
-- Name: Category_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: jrbuleo
--

ALTER SEQUENCE public."Category_id_seq" OWNED BY public."Category".id;


--
-- Name: Studio; Type: TABLE; Schema: public; Owner: jrbuleo
--

CREATE TABLE public."Studio" (
    id integer NOT NULL,
    name character varying NOT NULL,
    location character varying
);


ALTER TABLE public."Studio" OWNER TO jrbuleo;

--
-- Name: Studio_id_seq; Type: SEQUENCE; Schema: public; Owner: jrbuleo
--

CREATE SEQUENCE public."Studio_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Studio_id_seq" OWNER TO jrbuleo;

--
-- Name: Studio_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: jrbuleo
--

ALTER SEQUENCE public."Studio_id_seq" OWNED BY public."Studio".id;


--
-- Name: Videogame; Type: TABLE; Schema: public; Owner: jrbuleo
--

CREATE TABLE public."Videogame" (
    id integer NOT NULL,
    name character varying NOT NULL,
    description character varying,
    studio_id integer,
    category_id integer
);


ALTER TABLE public."Videogame" OWNER TO jrbuleo;

--
-- Name: Videogame_id_seq; Type: SEQUENCE; Schema: public; Owner: jrbuleo
--

CREATE SEQUENCE public."Videogame_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Videogame_id_seq" OWNER TO jrbuleo;

--
-- Name: Videogame_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: jrbuleo
--

ALTER SEQUENCE public."Videogame_id_seq" OWNED BY public."Videogame".id;


--
-- Name: Category id; Type: DEFAULT; Schema: public; Owner: jrbuleo
--

ALTER TABLE ONLY public."Category" ALTER COLUMN id SET DEFAULT nextval('public."Category_id_seq"'::regclass);


--
-- Name: Studio id; Type: DEFAULT; Schema: public; Owner: jrbuleo
--

ALTER TABLE ONLY public."Studio" ALTER COLUMN id SET DEFAULT nextval('public."Studio_id_seq"'::regclass);


--
-- Name: Videogame id; Type: DEFAULT; Schema: public; Owner: jrbuleo
--

ALTER TABLE ONLY public."Videogame" ALTER COLUMN id SET DEFAULT nextval('public."Videogame_id_seq"'::regclass);


--
-- Data for Name: Category; Type: TABLE DATA; Schema: public; Owner: jrbuleo
--

COPY public."Category" (id, name) FROM stdin;
1	Cars
2	Platforms
3	Rpg
4	Shooter
\.


--
-- Data for Name: Studio; Type: TABLE DATA; Schema: public; Owner: jrbuleo
--

COPY public."Studio" (id, name, location) FROM stdin;
1	Ubisoft	France
2	Arenanet	Seattle
3	Activision	Santa Monica
4	Square Enix	Tokyo
\.


--
-- Data for Name: Videogame; Type: TABLE DATA; Schema: public; Owner: jrbuleo
--

COPY public."Videogame" (id, name, description, studio_id, category_id) FROM stdin;
1	Final Fantasy VII	The best game	1	1
2	Final Fantasy I	The first FF	1	1
3	Final Fantasy II	The second FF	1	1
4	Final Fantasy III	The third one :D	3	4
\.


--
-- Name: Category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jrbuleo
--

SELECT pg_catalog.setval('public."Category_id_seq"', 4, true);


--
-- Name: Studio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jrbuleo
--

SELECT pg_catalog.setval('public."Studio_id_seq"', 4, true);


--
-- Name: Videogame_id_seq; Type: SEQUENCE SET; Schema: public; Owner: jrbuleo
--

SELECT pg_catalog.setval('public."Videogame_id_seq"', 4, true);


--
-- Name: Category Category_pkey; Type: CONSTRAINT; Schema: public; Owner: jrbuleo
--

ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "Category_pkey" PRIMARY KEY (id);


--
-- Name: Studio Studio_pkey; Type: CONSTRAINT; Schema: public; Owner: jrbuleo
--

ALTER TABLE ONLY public."Studio"
    ADD CONSTRAINT "Studio_pkey" PRIMARY KEY (id);


--
-- Name: Videogame Videogame_pkey; Type: CONSTRAINT; Schema: public; Owner: jrbuleo
--

ALTER TABLE ONLY public."Videogame"
    ADD CONSTRAINT "Videogame_pkey" PRIMARY KEY (id);


--
-- Name: Videogame Videogame_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jrbuleo
--

ALTER TABLE ONLY public."Videogame"
    ADD CONSTRAINT "Videogame_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public."Category"(id);


--
-- Name: Videogame Videogame_studio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jrbuleo
--

ALTER TABLE ONLY public."Videogame"
    ADD CONSTRAINT "Videogame_studio_id_fkey" FOREIGN KEY (studio_id) REFERENCES public."Studio"(id);


--
-- PostgreSQL database dump complete
--

